### ISSUE TITLE
Remove Furry Bot

### ISSUE THREAD

**Issue by fangmarks** [Gideon-Foxo/furry-bots#2]
Since [Furry Bot has been shut down](https://furry.bot), it should probably be taken off the List?

**Comment by Gideon-Foxo** [comment]
I only just realized yesterday (the day before you made this PR, yes it took me 2 days to make this) that it had been shut down. Last time I checked on its down time it was because of broken stuff and they where going to get it working. I have removed with the latest update https://github.com/Gideon-foxo/furry-bots/commit/0729eb59a9ca41e8a5a4c77157eb8275e3bb3154
