### ISSUE TITLE
Nyx

### ISSUE THREAD

**Issue by sylviiu** [Gideon-Foxo/furry-bots#22]
~~i've unfortunately sunsetted nyx for some time within the week, and have already removed the bot listing from all of the bot lists that i was able to find.~~
![image](https://github.com/Gideon-Foxo/furry-bots/assets/95180094/eb2537fd-2975-4f13-b601-99824793dab2)

~~maybe eventually i'll revive the project (or end up collaborating on another bot)? just not in a *good* spot to continue the project on my own :(~~

**update:** nyx is going to go through an entire rewrite with a new direction; the bot is still off of most bot lists, so it won't be public for now. i don't know if you'd still remove it from here? but yeah, just giving an update

**Comment by Gideon-Foxo** [comment]
Hi! Thanks for reaching out. Their are 3 main criteria for the list;

- The bot must be publicly findable. This means it has to be on a list somewhere and can be found, not just word of mouth.
- The bot must be maintained, aka its online and functions/responds to commands
- It must be verified with Discord, this is mainly because there are so many really small bots or bots that are not built in a very sustainable way and I do not care to track bots under 75 or so servers.

Given that Nyx still meets all of these items I see no reason to remove it at this time. However if it does go offline for an extended period of time then it will get removed. Whenever I update the list I check to see if any of the bots are offline and I give it a role. If its offline three times when I go to update the list (as indicated by its roles) then I remove it from the list until it returns to being online in a somewhat stable state. I do plan to automate this checking but it is a low priority for me right now.

I tend to try to update this list weekly but iv been very busy lately, just went to a furcon and had a little bit of work so I have been fairly exhausted but it will get updated very soon. Developing for Discord can be very exhausting and I urge you to do what is best for yourself. I have 2 bots on this list myself, I get it, it can be very frustrating and exhausting, but at the end of the day you still have to look out for yourself and figure out what is best for you to do.

You do not need to reply if you wish, I do keep light tabs on all the bots on and some not on this list to make sure I am not updating bots that are not maintained anymore. Wishing you the best of luck in whatever choice or direction you choice! Thanks for the heads up

**Comment by sylviiu** [comment]
~~i swear everyone i know went to a furcon just recently oml i need to save up at some point~~

as a sidenote, you could probably automate the list with github actions if anything? that would keep an easier tab on the bots.

as of now i don't have any plans to take it offline; it still "works" in its current state and a lot more people were using it for core server structure than i was anticipating, so it's not going offline.

the bot still has been removed from the server lists i were able to find, but can still be invited through that "add to server" button regardless; that's the only way it can be found (to my knowledge)

but yeah, if possible, i'd like to keep it there now :) i'm still on the drawing board figuring out which way i wanna go haha

thank you!

**Comment by Gideon-Foxo** [comment]
The bot is still on [Discords app directory](https://discord.com/application-directory/600206352916414464) so that is good enough for me, I just need to link/point to a page listing of the bot.

I think you mentioned this in another issue but never expounded apron it when I asked, I am not really sure how that would/could help me? I have not looked into it but fetching the server counts is manual and I would have to scrape the invite for it and I am not sure Discord would like me doing that. Nor do I think github would let me automate that without my own code, and everything else like adding or removing or checking up time n stuff is kind of manual, I could automate part of it I think it would just have to be my own code interfacing with github I think unless I am just wrong. But again its a fairly low priority for me, I have 4 other bots/projects that im working on right now and automating this is just so low for me right now I have not looked into it yet.

**Comment by sylviiu** [comment]
I...don't recall mentioning that, mainly because I also just recently started utilizing CI/CD myself haha

Most discord bot lists offer a public API for you to access, which usually also returns the bot's last reported server count -- I did implement top.gg's API with Nyx for bot lookup before, but somewhere it broke. It *would* require your own code though, which is definitely a downside for this, I can't blame you for the low priority.

...i also entirely forgot discord had an app directory lol; i won't remove it from there.

**Comment by Gideon-Foxo** [comment]
I just checked and it was another dev I was thinking about that had asked about the automation, my bad!

That in itself is the problem. Not all bots are on topgg, not all bots upload their stats and those that do... well I would have to verify they are even accrete or being maintained. Updating server count is a pretty low priority to most devs so if it breaks it might be missed or would take a long time to get fixed. So it does not really make sense to do this.
